hologram:
  offset-y: 1.1

  item:
    offset-y: 0.75
    scale: 0.3

  text:
    shadow: true
    billboard: VERTICAL

    background:
      enabled: false
      color: "#000000" # TRANSPARENT or HEX color

    lines:
      - "&#55FF55{item}"
      - "&#FFFF55{price}$"

formatting:
  # CLOCK_DD_HH_MM_SS -> 01:12:30:45 (days:hours:minutes:seconds)
  # CLOCK_HH_MM_SS -> 36:30:45 (total hours:minutes:seconds)
  # CLOCK_MM_SS -> 2190:45 (total minutes:seconds)
  #
  # WORDS_FULL -> 1 day 12 hours 30 minutes 45 seconds
  # WORDS_COMPACT -> 1d 12h 30m 45s
  #
  # HOURS_ONLY -> 36h
  # MINUTES_ONLY -> 2190m
  # SECONDS_ONLY -> 131445s
  time-format: "WORDS_COMPACT"
  amount-format: "COMPACT"

version: '1'